---
# pre-commit is a tool to perform a predefined set of tasks manually and/or
# automatically before git commits are made.
#
# Config reference: https://pre-commit.com/#pre-commit-configyaml---top-level
#
# Common tasks
#
# - Run on all files:   pre-commit run --all-files
# - Register git hooks: pre-commit install --install-hooks
#
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
# See https://pre-commit.com for more information
# spell-checker: disable
# See https://pre-commit.com for more information
repos:
  - repo: local
    hooks:
      - id: commitlint
        name: commitlint
        description: Ensure commit message adheres to conventional commits
        language: node
        entry: commitlint --edit
        additional_dependencies:
          - "@commitlint/cli"
          - "@commitlint/config-conventional"
        stages:
          - commit-msg

      - id: commitlint_recent
        name: commitlint recent
        description: ensure all recent commit messages adhere to conventional commits
        language: node
        entry: bash -c 'commitlint --from $(git merge-base HEAD origin/main)'
        always_run: true
        pass_filenames: false
        additional_dependencies:
          - "@commitlint/cli"
          - "@commitlint/config-conventional"
        stages:
          - manual

      - id: markdownlint
        name: markdownlint
        description: Checks the style of Markdown files
        entry: markdownlint
        language: node
        additional_dependencies:
          - markdownlint-cli@0.32.2
        types:
          - markdown
        stages:
          - commit

      - id: trufflehook
        name: TruffleHog
        description: Detect secrets within Repository
        entry: trufflesecurity/trufflehog:latest git file:///src --only-verified --fail --no-update
        always_run: true
        language: docker_image
        pass_filenames: false
        stages: ["commit", "push"]

      - id: kics
        name: Kics scan
        language: docker_image
        entry: checkmarx/kics:latest scan -p /src --ci --log-level WARN
        verbose: true
        stages:
          - push
